export const hiragana = [
  {
    character: "あ",
    romani: "a",
    sound: "a.mp3",
    color: "hsl(3, 100%, 20%)",
  },
  {
    character: "い",
    romani: "i",
    sound: "i.mp3",
    color: "hsl(3, 100%, 30%)",
  },
  {
    character: "う",
    romani: "u",
    sound: "u.mp3",
    color: "hsl(3, 100%, 40%)",
  },
  {
    character: "え",
    romani: "e",
    sound: "e.mp3",
    color: "hsl(3, 100%, 50%)",
  },
  {
    character: "お",
    romani: "o",
    sound: "o.mp3",
    color: "hsl(3, 100%, 60%)",
  },
  {
    character: "か",
    romani: "ka",
    sound: "ka.mp3",
    color: "hsl(221, 100%, 20%)",
  },
  {
    character: "き",
    romani: "ki",
    sound: "ki.mp3",
    color: "hsl(221, 100%, 30%)",
  },
  {
    character: "く",
    romani: "ku",
    sound: "ku.mp3",
    color: "hsl(221, 100%, 40%)",
  },
  {
    character: "け",
    romani: "ke",
    sound: "ke.mp3",
    color: "hsl(221, 100%, 50%)",
  },
  {
    character: "こ",
    romani: "ko",
    sound: "ko.mp3",
    color: "hsl(221, 100%, 60%)",
  },
  {
    character: "さ",
    romani: "sa",
    sound: "sa.mp3",
    color: "hsl(147, 100%, 20%)",
  },
  {
    character: "し",
    romani: "shi",
    sound: "shi.mp3",
    color: "hsl(147, 100%, 30%)",
  },
  {
    character: "す",
    romani: "su",
    sound: "su.mp3",
    color: "hsl(147, 100%, 40%)",
  },
  {
    character: "せ",
    romani: "se",
    sound: "se.mp3",
    color: "hsl(147, 100%, 50%)",
  },
  {
    character: "そ",
    romani: "so",
    sound: "so.mp3",
    color: "hsl(147, 100%, 60%)",
  },
  {
    character: "た",
    romani: "ta",
    sound: "ta.mp3",
    color: "hsl(181,100%,20%)",
  },
  {
    character: "ち",
    romani: "chi",
    sound: "chi.mp3",
    color: "hsl(181,100%,30%)",
  },
  {
    character: "つ",
    romani: "tsu",
    sound: "tsu.mp3",
    color: "hsl(181,100%,40%)",
  },
  {
    character: "て",
    romani: "te",
    sound: "te.mp3",
    color: "hsl(181,100%,50%)",
  },
  {
    character: "と",
    romani: "to",
    sound: "to.mp3",
    color: "hsl(181,100%,60%)",
  },
  {
    character: "な",
    romani: "na",
    sound: "na.mp3",
    color: "hsl(61, 100%, 20%)",
  },
  {
    character: "に",
    romani: "ni",
    sound: "ni.mp3",
    color: "hsl(61, 100%, 30%)",
  },
  {
    character: "ぬ",
    romani: "nu",
    sound: "nu.mp3",
    color: "hsl(61, 100%, 40%)",
  },
  {
    character: "ね",
    romani: "ne",
    sound: "ne.mp3",
    color: "hsl(61, 100%, 50%)",
  },
  {
    character: "の",
    romani: "no",
    sound: "no.mp3",
    color: "hsl(61, 100%, 60%)",
  },
  {
    character: "は",
    romani: "ha",
    sound: "ha.mp3",
    color: "hsl(327, 89%, 20%)",
  },
  {
    character: "ひ",
    romani: "hi",
    sound: "hi.mp3",
    color: "hsl(327, 89%, 30%)",
  },
  {
    character: "ふ",
    romani: "fu",
    sound: "fu.mp3",
    color: "hsl(327, 89%, 40%)",
  },
  {
    character: "へ",
    romani: "he",
    sound: "he.mp3",
    color: "hsl(327, 89%, 50%)",
  },
  {
    character: "ほ",
    romani: "ho",
    sound: "ho.mp3",
    color: "hsl(327, 89%, 60%)",
  },
  {
    character: "ま",
    romani: "ma",
    sound: "ma.mp3",
    color: "hsl(25, 78%, 20%)",
  },
  {
    character: "み",
    romani: "mi",
    sound: "mi.mp3",
    color: "hsl(25, 78%, 30%)",
  },
  {
    character: "む",
    romani: "mu",
    sound: "mu.mp3",
    color: "hsl(25, 78%, 40%)",
  },
  {
    character: "め",
    romani: "me",
    sound: "me.mp3",
    color: "hsl(25, 78%, 50%)",
  },
  {
    character: "も",
    romani: "mo",
    sound: "mo.mp3",
    color: "hsl(25, 78%, 60%)",
  },
  {
    character: "や",
    romani: "ya",
    sound: "ya.mp3",
    color: "hsl(294, 78%, 20%)",
  },
  {
    character: "ゆ",
    romani: "yu",
    sound: "yu.mp3",
    color: "hsl(294, 78%, 40%)",
  },
  {
    character: "よ",
    romani: "yo",
    sound: "yo.mp3",
    color: "hsl(294, 78%, 60%)",
  },
  {
    character: "ら",
    romani: "ra",
    sound: "ra.mp3",
    color: "hsl(96, 100%, 20%)",
  },
  {
    character: "り",
    romani: "ri",
    sound: "ri.mp3",
    color: "hsl(96, 100%, 30%)",
  },
  {
    character: "る",
    romani: "ru",
    sound: "ru.mp3",
    color: "hsl(96, 100%, 40%)",
  },
  {
    character: "れ",
    romani: "re",
    sound: "re.mp3",
    color: "hsl(96, 100%, 50%)",
  },
  {
    character: "ろ",
    romani: "ro",
    sound: "ro.mp3",
    color: "hsl(96, 100%, 60%)",
  },
  {
    character: "わ",
    romani: "wa",
    sound: "wa.mp3",
    color: "hsl(249, 50%, 20%)",
  },
  {
    character: "を",
    romani: "wo",
    sound: "wo.mp3",
    color: "hsl(249, 50%, 60%)",
  },
  {
    character: "ん",
    romani: "hm",
    sound: "hm.mp3",
    color: "hsl(0, 50%, 20%)",
  },
];
